<a href="https://colab.research.google.com/github/CainaRosePaul/GMAIL-SPAM-DETECTION/blob/main/DIABETES_DETECTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DIABETES DETECTION**

**IMPORTING THE LIBRARY**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


**IMPORTING THE DATASET**

In [ ]:
dataset=pd.read_csv("Diabetes.csv")
dataset.head(768)

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

**ANALYSE OF DATASET**

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   blood pressure            768 non-null    int64  
 3   skin thickness            768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
blood pressure              0
skin thickness              0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
X=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

In [ ]:
print(X)

     Pregnancies  Glucose  blood pressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148              72  ...  33.6                     0.627   50
1              1       85              66  ...  26.6                     0.351   31
2              8      183              64  ...  23.3                     0.672   32
3              1       89              66  ...  28.1                     0.167   21
4              0      137              40  ...  43.1                     2.288   33
..           ...      ...             ...  ...   ...                       ...  ...
763           10      101              76  ...  32.9                     0.171   63
764            2      122              70  ...  36.8                     0.340   27
765            5      121              72  ...  26.2                     0.245   30
766            1      126              60  ...  30.1                     0.349   47
767            1       93              70  ...  30.4                     0.3

In [ ]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


**Train_Test_Split**

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=0)

**Logistic Regrssion**

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred=lr.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[98, 18],
       [ 9, 29]])

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuarcy: ",round(accuracy_score(y_pred,y_test),2)*100)

Accuarcy:  82.0


In [ ]:
pd.DataFrame({"ORIGINAL DATASET":y_test,"PREDICTED DATASET":y_pred})

ORIGINAL DATASET  PREDICTED DATASET
661                 1                  1
122                 0                  0
113                 0                  0
14                  1                  1
529                 0                  0
..                ...                ...
476                 1                  0
482                 0                  0
230                 1                  1
527                 0                  0
380                 0                  0

[154 rows x 2 columns]

**Random Forest Tree**

In [ ]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy",random_state=0)  
classifier.fit(X_train, y_train)  

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
y_pred=lr.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[98, 18],
       [ 9, 29]])

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuarcy: ",round(accuracy_score(y_pred,y_test),2)*100)

Accuarcy:  82.0


In [ ]:
pd.DataFrame({"ORIGINAL DATASET":y_test,"PREDICTED DATASET":y_pred})

ORIGINAL DATASET  PREDICTED DATASET
661                 1                  1
122                 0                  0
113                 0                  0
14                  1                  1
529                 0                  0
..                ...                ...
476                 1                  0
482                 0                  0
230                 1                  1
527                 0                  0
380                 0                  0

[154 rows x 2 columns]

**KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred=lr.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[98, 18],
       [ 9, 29]])

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuarcy: ",round(accuracy_score(y_pred,y_test),2)*100)

Accuarcy:  82.0


In [ ]:
pd.DataFrame({"ORIGINAL DATASET":y_test,"PREDICTED DATASET":y_pred})

ORIGINAL DATASET  PREDICTED DATASET
661                 1                  1
122                 0                  0
113                 0                  0
14                  1                  1
529                 0                  0
..                ...                ...
476                 1                  0
482                 0                  0
230                 1                  1
527                 0                  0
380                 0                  0

[154 rows x 2 columns]